name: The most popular blog
description: Blogging about programming and investing
meta_description: "Blog of Artem"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "https://artemme.github.io.com"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Artem"

# Disqus config
disqus-shortname: ""
